# Netlify configuration file
[build]
  publish = "client/public"
  command = "npm run start"
  base = "client/"

# Redirects configuration for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200